services:
  repozitorij-radova:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${USERNAME}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${DB}
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "5432:5432"