info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  plugin:
    databasemigration:
      updateOnStart: true
      updateOnStartFileName: changelog.groovy
  mime:
    types:
      all:
        - '*/*'
      json:
        - application/json
        - text/json
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: json


hibernate:
  dialect: org.hibernate.dialect.PostgreSQL10Dialect
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false


server:
  servlet:
    context-path: /api

environments:
  development:
    dataSource:
      url: jdbc:postgresql://localhost:5432/repozitorij_radova
      logSql: true
      username: svc_repozitorijradova
      password: root
      pooled: true
      jmxExport: true
      dbCreate: none
  production:
    dataSource:
      url: jdbc:postgresql://postgres:5432/${DB_NAME}
      driverClassName: org.postgresql.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      pooled: true
      jmxExport: true
      dbCreate: none
